sudo: required
sevices:
  - docker

before_install:
  - docker build -t kartheekgopal/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true kartheekgopal/docker-frontend npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-265208151699"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"